name: Pre Production CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Download uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Lint code
        run: uv run ruff check

      - name: Check format
        run: uv run ruff format --check
