name: Deploy project

on:
  workflow_run:
    workflows: ["Pre Production CI"]
    types:
      - completed

jobs:
  Build-Project:
    if: ${{  github.event.workflow_run.conclusion == 'success' }}
    environment: production

    runs-on: ubuntu-latest

    steps:
      - name: Upload to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          ssh -i ./private_key.pem $SERVER_USER@$SERVER_IP '
            pushd ./pdf-service > /dev/null &&
            git pull &&
            .venv/bin/uv sync &&
            popd > /dev/null &&
            sudo systemctl restart pdf-service.service
          '
